---
- name: Azure Login and Perform Tasks
  hosts: localhost
  gather_facts: false
  vars:
    azure_subscription_id: "2c5ca720-b504-43bd-9d0f-8d577a2230de"
    azure_client_id: "8e09ef07-fdd5-4412-b624-b65a51423f55"
    azure_client_secret: "fZy8Q~SW22r8EnN39NQMpdsUkO8sBHsQcOoK7ca4"
    azure_tenant_id: "77fa8e53-4a9f-45d6-8b94-4a6e4d12f418"
  tasks:
    - name: Authenticate with Azure
      azure.azcollection.azure_rm_login:
        client_id: "{{ azure_client_id }}"
        client_secret: "{{ azure_client_secret }}"
        tenant: "{{ azure_tenant_id }}"
      delegate_to: localhost
    - name: Stop the VM for Fortes
      shell: "az vm stop --name avd-fortes-0.fortes.local --resource-group rg-fortes --subscription 2c5ca720-b504-43bd-9d0f-8d577a2230de --no-wait"
