---
- name: win_reboot
  hosts: avd-fortes-0.fortes.local
  become: false
  gather_facts: false
  tasks:
    - name: reboot host(s)
      ansible.windows.win_reboot:
        msg: "reboot by Ansible"
        pre_reboot_delay: 15
        post_reboot_delay: 30
