---
- name: Shutdown Windows VM in Azure
  hosts: localhost
  connection: local
  tasks:
    - name: Login to Azure Cli
      shell: groupadd sonar && useradd -c "SonarQube - User" -d /opt/sonarqube/ -g sonar sonar
      ignore_errors: yes
    - name: Shutdown Azure VM
      shell: /bin/az vm stop --name avd-fortes-0.fortes.local --resource-group rg-fortes --subscription 2c5ca720-b504-43bd-9d0f-8d577a2230de --no-wait
